fixing error if bucket already owned

diff --git a/gitops/doc-bot/templates/setup-jobs.yaml b/gitops/doc-bot/templates/setup-jobs.yaml
--- a/gitops/doc-bot/templates/setup-jobs.yaml
+++ b/gitops/doc-bot/templates/setup-jobs.yaml
@@ -66,12 +66,14 @@ spec:
               echo "AWS Config file:"
               cat ${AWS_CONFIG_FILE}
 
-              echo ">> Creating S3 bucket..."
+              echo ">>>>>> Creating S3 bucket..."
               # Create a bucket
-              output=$(aws s3api create-bucket --bucket ${AWS_S3_BUCKET} --endpoint-url "{{ .Values.modelConnection.scheme }}://${AWS_S3_ENDPOINT}")
+              output=$(aws s3api create-bucket --bucket ${AWS_S3_BUCKET} --endpoint-url "{{ .Values.modelConnection.scheme }}://${AWS_S3_ENDPOINT}" 2>&1)
+              exit_code=$?
               echo "Output: $output"
 
               # Check for the specific error
+              echo ">>>>>> Checking for error..."
               if echo "${output}" | grep -q "BucketAlreadyOwnedByYou"; then
                   echo "Bucket ${AWS_S3_BUCKET} already owned by you. Continuing..."
               elif echo "${output}" | grep -q "Error"; then
@@ -82,6 +84,7 @@ spec:
               fi
 
               # Upload the model to files folder in the bucket
+              echo ">>>>>> Syncing model files to S3..."
               aws s3 sync ${MODEL_ID} s3://${AWS_S3_BUCKET}/${MODEL_ROOT}/${MODEL_ID}/ --endpoint-url "https://${AWS_S3_ENDPOINT}" 
           command:
             - /bin/bash
